#ifndef BUBBLETEA_H
#define BUBBLETEA_H

#define BUBBLETEA_BASE 0x10080000
#define BUBBLETEA_RUN (BUBBLETEA_BASE + 0x0)
#define BUBBLETEA_DONE (BUBBLETEA_BASE + 0x1)
#define BUBBLETEA_LOAD_BITSTREAM (BUBBLETEA_BASE + 0x2)
#define BUBBLETEA_LOAD_BITSTREAM_DONE (BUBBLETEA_BASE + 0x3)
#define BUBBLETEA_CONFIGURATION_DONE (BUBBLETEA_BASE + 0x4)
#define BUBBLETEA_BITSTREAM_BASE_ADDR (BUBBLETEA_BASE + 0x10)

#endif